/*
 * This file is part of OpenCollar.Extensions.Logging.
 *
 * OpenCollar.Extensions.Logging is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * OpenCollar.Extensions.Logging is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * OpenCollar.Extensions.Logging.  If not, see <https://www.gnu.org/licenses/>.
 *
 * Copyright © 2020 Jonathan Evans (jevans@open-collar.org.uk).
 */

using System;
using System.Globalization;

using JetBrains.Annotations;

namespace OpenCollar.Extensions.Logging
{
    /// <summary>
    ///     A class used to represent the scope of an operation and automatically write entry and exit messages to the
    ///     log specified.
    /// </summary>
    /// <remarks>
    ///     Use <see cref="IDisposable.Dispose" /> to exit the scope.
    /// </remarks>
    /// <seealso cref="OpenCollar.Extensions.Disposable" />
    internal sealed class OperationScope : Disposable
    {
        private const string _operationScopeMessageKey = @"operation-scope.message";

        /// <summary>
        ///     The context used for the scope.
        /// </summary>
        private readonly LoggingContext _currentContext;

        /// <summary>
        ///     The operation scope message at the start of the scope.
        /// </summary>
        [CanBeNull]
        private readonly string? _currentOperationScopeMessage;

        /// <summary>
        ///     A function that returns additional information to be recorded with the "finish" log written at the end
        ///     of the operation.
        /// </summary>
        [CanBeNull]
        private readonly Func<string>? _getAdditionalEndMessage;

        /// <summary>
        ///     The logger to which messages will be written.
        /// </summary>
        [NotNull]
        private readonly Microsoft.Extensions.Logging.ILogger _logger;

        /// <summary>
        ///     The level at which to write to the log.
        /// </summary>
        private readonly Microsoft.Extensions.Logging.LogLevel _logLevel;

        /// <summary>
        ///     The fragment of message to write. Should be formed to fit into a sentence of the form "Starting XXX."
        /// </summary>
        [NotNull]
        private readonly string _message;

        /// <summary>
        ///     The scope (if any) generated by the <see cref="Microsoft.Extensions.Logging.ILogger.BeginScope{T}(T)" /> method.
        /// </summary>
        [CanBeNull]
        private readonly IDisposable? _scope;

        /// <summary>
        ///     The UTC date/time at which the operation started.
        /// </summary>
        private readonly DateTime _start;

        /// <summary>
        ///     Initializes a new instance of the <see cref="OperationScope" /> class.
        /// </summary>
        /// <param name="logger">
        ///     The logger to which messages will be written.
        /// </param>
        /// <param name="beginLogLevel">
        ///     The level at which to write the log message at the start of the operation.
        /// </param>
        /// <param name="endLogLevel">
        ///     The log level to use to write the message at the end of the operation.
        /// </param>
        /// <param name="scopeName">
        ///     The fragment of message to write. Should be formed to fit into a sentence of the form "Starting XXX."
        /// </param>
        /// <param name="getAdditionalEndMessage">
        ///     An action that will be called when the operation has finished to get any additional details of the operation.
        /// </param>
        internal OperationScope([NotNull] Microsoft.Extensions.Logging.ILogger logger, Microsoft.Extensions.Logging.LogLevel beginLogLevel, Microsoft.Extensions.Logging.LogLevel endLogLevel, [NotNull] string scopeName, [CanBeNull] Func<string>? getAdditionalEndMessage)
        {
            _logLevel = endLogLevel;

            _start = DateTime.UtcNow;
            _logger = logger;
            _message = scopeName;
            _getAdditionalEndMessage = getAdditionalEndMessage;

            var generatedMessage = string.Concat(@"BEGIN: ", scopeName, @".");
            _scope = _logger.BeginScope(generatedMessage);

            if(beginLogLevel != Microsoft.Extensions.Logging.LogLevel.None)
            {
                _logger.Log(beginLogLevel, generatedMessage);
            }

            _currentContext = LoggingContext.Current();
            _currentOperationScopeMessage = _currentContext[_operationScopeMessageKey];
            _currentContext.AppendInfo(_operationScopeMessageKey, scopeName);
        }

        /// <summary>
        ///     Releases unmanaged and - optionally - managed resources.
        /// </summary>
        /// <param name="disposing">
        ///     <see langword="true" /> to release both managed and unmanaged resources; <see langword="false" /> to
        ///     release only unmanaged resources.
        /// </param>
        protected override void Dispose(bool disposing)
        {
            if(disposing && (_logLevel != Microsoft.Extensions.Logging.LogLevel.None))
            {
                // Capture the time.
                var duration = DateTime.UtcNow - _start;

                // Generate the message
                var message = string.Concat(@"END: ", _message, @".  Duration: ", duration.TotalMilliseconds.ToString("N0", CultureInfo.InvariantCulture), @"ms.");

                // Generate additional details to add to the message.
                if(!ReferenceEquals(_getAdditionalEndMessage, null))
                {
                    var additionalMessage = _getAdditionalEndMessage();
                    if(!string.IsNullOrWhiteSpace(additionalMessage))
                    {
                        message = string.Concat(message, " ", additionalMessage);
                    }
                }

                // Revert the operation scope message in the context back to it's original value.
                if(string.IsNullOrWhiteSpace(_currentOperationScopeMessage))
                {
                    _currentContext.ClearInfo(_operationScopeMessageKey);
                }
                else
                {
                    _currentContext.AppendInfo(_operationScopeMessageKey, _currentOperationScopeMessage);
                }

                // Record the message.
                _logger.Log(_logLevel, message);

                // Complete the logging scope
                if(!ReferenceEquals(_scope, null))
                {
                    _scope.Dispose();
                }
            }

            base.Dispose(disposing);
        }
    }
}